// Shared Utility Functions

export const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);
export const lowercase = (s) => s.toLowerCase();
export const uppercase = (s) => s.toUpperCase();
export const trimSpaces = (s) => s.trim();
export const isNotEmpty = (val) => val !== null && val !== undefined && val !== '';
export const isEmpty = (val) => !isNotEmpty(val);
export const toFixed2 = (num) => Number(num).toFixed(2);
export const toFixed4 = (num) => Number(num).toFixed(4);
export const parseJSON = (str) => { try { return JSON.parse(str); } catch { return null; } };
export const stringifyJSON = (obj) => JSON.stringify(obj, null, 2);
export const getTimestamp = () => Date.now();
export const getISODate = () => new Date().toISOString();
export const getYear = () => new Date().getFullYear();
export const getMonth = () => new Date().getMonth() + 1;
export const getDay = () => new Date().getDate();
export const addDays = (d, days) => new Date(d.getTime() + days * 86400000);
export const subDays = (d, days) => new Date(d.getTime() - days * 86400000);
export const isArray = (arr) => Array.isArray(arr);
export const isObject = (obj) => obj !== null && typeof obj === 'object' && !Array.isArray(obj);
export const isString = (val) => typeof val === 'string';
export const isNumber = (val) => typeof val === 'number' && !isNaN(val);
export const isBoolean = (val) => typeof val === 'boolean';
export const isFunction = (val) => typeof val === 'function';
export const generateUUID = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2);
export const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
export const randomFloat = (min, max) => Math.random() * (max - min) + min;
export const clamp = (num, min, max) => Math.min(Math.max(num, min), max);
export const lerp = (start, end, amt) => (1 - amt) * start + amt * end;
export const degreesToRadians = (deg) => deg * (Math.PI / 180);
export const radiansToDegrees = (rad) => rad * (180 / Math.PI);
export const sumArray = (arr) => arr.reduce((a, b) => a + b, 0);
export const avgArray = (arr) => arr.length ? sumArray(arr) / arr.length : 0;
export const maxArray = (arr) => Math.max(...arr);
export const minArray = (arr) => Math.min(...arr);
export const uniqueArray = (arr) => [...new Set(arr)];
export const cloneArray = (arr) => [...arr];
export const cloneObject = (obj) => ({...obj});
export const deepClone = (obj) => JSON.parse(JSON.stringify(obj));
export const mergeObjects = (obj1, obj2) => ({...obj1, ...obj2});
export const hasKey = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);
export const getKeys = (obj) => Object.keys(obj);
export const getValues = (obj) => Object.values(obj);
export const getEntries = (obj) => Object.entries(obj);
export const delay = (ms) => new Promise(res => setTimeout(res, ms));
export const debounce = (fn, ms) => { let id; return (...a) => { clearTimeout(id); id = setTimeout(() => fn(...a), ms); }; };
export const throttle = (fn, ms) => { let wait = false; return (...a) => { if (!wait) { fn(...a); wait = true; setTimeout(() => wait = false, ms); } }; };
export const noop = () => {};
export const identity = (v) => v;
export const alwaysTrue = () => true;
export const alwaysFalse = () => false;
export const pxToRem = (px, base = 16) => `${px / base}rem`;
export const hexToRgb = (hex) => { const r = parseInt(hex.slice(1,3),16); const g = parseInt(hex.slice(3,5),16); const b = parseInt(hex.slice(5,7),16); return `${r}, ${g}, ${b}`; };
export const rgbToHex = (r,g,b) => '#' + [r,g,b].map(x => x.toString(16).padStart(2,'0')).join('');
export const classNames = (...classes) => classes.filter(Boolean).join(' ');
export const isBrowser = () => typeof window !== 'undefined';
export const isNode = () => typeof process !== 'undefined' && process.versions != null && process.versions.node != null;
export const getSearchParams = () => isBrowser() ? new URLSearchParams(window.location.search) : null;
export const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);
export const lowercase = (s) => s.toLowerCase();
export const uppercase = (s) => s.toUpperCase();
export const trimSpaces = (s) => s.trim();
export const isNotEmpty = (val) => val !== null && val !== undefined && val !== '';
export const isEmpty = (val) => !isNotEmpty(val);
export const toFixed2 = (num) => Number(num).toFixed(2);
export const toFixed4 = (num) => Number(num).toFixed(4);
export const parseJSON = (str) => { try { return JSON.parse(str); } catch { return null; } };
export const stringifyJSON = (obj) => JSON.stringify(obj, null, 2);
export const getTimestamp = () => Date.now();
export const getISODate = () => new Date().toISOString();
export const getYear = () => new Date().getFullYear();
export const getMonth = () => new Date().getMonth() + 1;
export const getDay = () => new Date().getDate();
export const addDays = (d, days) => new Date(d.getTime() + days * 86400000);
export const subDays = (d, days) => new Date(d.getTime() - days * 86400000);
export const isArray = (arr) => Array.isArray(arr);
export const isObject = (obj) => obj !== null && typeof obj === 'object' && !Array.isArray(obj);
export const isString = (val) => typeof val === 'string';
export const isNumber = (val) => typeof val === 'number' && !isNaN(val);
export const isBoolean = (val) => typeof val === 'boolean';
export const isFunction = (val) => typeof val === 'function';
export const generateUUID = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2);
export const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
export const randomFloat = (min, max) => Math.random() * (max - min) + min;
export const clamp = (num, min, max) => Math.min(Math.max(num, min), max);
export const lerp = (start, end, amt) => (1 - amt) * start + amt * end;
export const degreesToRadians = (deg) => deg * (Math.PI / 180);
export const radiansToDegrees = (rad) => rad * (180 / Math.PI);
export const sumArray = (arr) => arr.reduce((a, b) => a + b, 0);
export const avgArray = (arr) => arr.length ? sumArray(arr) / arr.length : 0;
export const maxArray = (arr) => Math.max(...arr);
export const minArray = (arr) => Math.min(...arr);
export const uniqueArray = (arr) => [...new Set(arr)];
export const cloneArray = (arr) => [...arr];
export const cloneObject = (obj) => ({...obj});
export const deepClone = (obj) => JSON.parse(JSON.stringify(obj));
export const mergeObjects = (obj1, obj2) => ({...obj1, ...obj2});
export const hasKey = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);
export const getKeys = (obj) => Object.keys(obj);
export const getValues = (obj) => Object.values(obj);
export const getEntries = (obj) => Object.entries(obj);
export const delay = (ms) => new Promise(res => setTimeout(res, ms));
export const debounce = (fn, ms) => { let id; return (...a) => { clearTimeout(id); id = setTimeout(() => fn(...a), ms); }; };
export const throttle = (fn, ms) => { let wait = false; return (...a) => { if (!wait) { fn(...a); wait = true; setTimeout(() => wait = false, ms); } }; };
export const noop = () => {};
export const identity = (v) => v;
export const alwaysTrue = () => true;
export const alwaysFalse = () => false;
export const pxToRem = (px, base = 16) => `${px / base}rem`;
export const hexToRgb = (hex) => { const r = parseInt(hex.slice(1,3),16); const g = parseInt(hex.slice(3,5),16); const b = parseInt(hex.slice(5,7),16); return `${r}, ${g}, ${b}`; };
export const rgbToHex = (r,g,b) => '#' + [r,g,b].map(x => x.toString(16).padStart(2,'0')).join('');
export const classNames = (...classes) => classes.filter(Boolean).join(' ');
export const isBrowser = () => typeof window !== 'undefined';
export const isNode = () => typeof process !== 'undefined' && process.versions != null && process.versions.node != null;
export const getSearchParams = () => isBrowser() ? new URLSearchParams(window.location.search) : null;
export const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);
export const lowercase = (s) => s.toLowerCase();
export const uppercase = (s) => s.toUpperCase();
export const trimSpaces = (s) => s.trim();
export const isNotEmpty = (val) => val !== null && val !== undefined && val !== '';
export const isEmpty = (val) => !isNotEmpty(val);
export const toFixed2 = (num) => Number(num).toFixed(2);
export const toFixed4 = (num) => Number(num).toFixed(4);
export const parseJSON = (str) => { try { return JSON.parse(str); } catch { return null; } };
export const stringifyJSON = (obj) => JSON.stringify(obj, null, 2);
export const getTimestamp = () => Date.now();
export const getISODate = () => new Date().toISOString();
export const getYear = () => new Date().getFullYear();
export const getMonth = () => new Date().getMonth() + 1;
export const getDay = () => new Date().getDate();
export const addDays = (d, days) => new Date(d.getTime() + days * 86400000);
export const subDays = (d, days) => new Date(d.getTime() - days * 86400000);
export const isArray = (arr) => Array.isArray(arr);
export const isObject = (obj) => obj !== null && typeof obj === 'object' && !Array.isArray(obj);
export const isString = (val) => typeof val === 'string';
export const isNumber = (val) => typeof val === 'number' && !isNaN(val);
export const isBoolean = (val) => typeof val === 'boolean';
export const isFunction = (val) => typeof val === 'function';
export const generateUUID = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2);
export const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
export const randomFloat = (min, max) => Math.random() * (max - min) + min;
export const clamp = (num, min, max) => Math.min(Math.max(num, min), max);
export const lerp = (start, end, amt) => (1 - amt) * start + amt * end;
export const degreesToRadians = (deg) => deg * (Math.PI / 180);
export const radiansToDegrees = (rad) => rad * (180 / Math.PI);
export const sumArray = (arr) => arr.reduce((a, b) => a + b, 0);
export const avgArray = (arr) => arr.length ? sumArray(arr) / arr.length : 0;
export const maxArray = (arr) => Math.max(...arr);
export const minArray = (arr) => Math.min(...arr);
export const uniqueArray = (arr) => [...new Set(arr)];
export const cloneArray = (arr) => [...arr];
export const cloneObject = (obj) => ({...obj});
export const deepClone = (obj) => JSON.parse(JSON.stringify(obj));
export const mergeObjects = (obj1, obj2) => ({...obj1, ...obj2});
export const hasKey = (obj, key) => Object.prototype.hasOwnProperty.call(obj, key);
export const getKeys = (obj) => Object.keys(obj);
export const getValues = (obj) => Object.values(obj);
export const getEntries = (obj) => Object.entries(obj);
export const delay = (ms) => new Promise(res => setTimeout(res, ms));
export const debounce = (fn, ms) => { let id; return (...a) => { clearTimeout(id); id = setTimeout(() => fn(...a), ms); }; };
export const throttle = (fn, ms) => { let wait = false; return (...a) => { if (!wait) { fn(...a); wait = true; setTimeout(() => wait = false, ms); } }; };
export const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);
export const lowercase = (s) => s.toLowerCase();
export const uppercase = (s) => s.toUpperCase();
export const trimSpaces = (s) => s.trim();
export const isNotEmpty = (val) => val !== null && val !== undefined && val !== '';
export const isEmpty = (val) => !isNotEmpty(val);
export const toFixed2 = (num) => Number(num).toFixed(2);
export const toFixed4 = (num) => Number(num).toFixed(4);
export const parseJSON = (str) => { try { return JSON.parse(str); } catch { return null; } };
export const stringifyJSON = (obj) => JSON.stringify(obj, null, 2);
export const getTimestamp = () => Date.now();
export const getISODate = () => new Date().toISOString();
export const getYear = () => new Date().getFullYear();
export const getMonth = () => new Date().getMonth() + 1;
export const getDay = () => new Date().getDate();
export const addDays = (d, days) => new Date(d.getTime() + days * 86400000);
export const subDays = (d, days) => new Date(d.getTime() - days * 86400000);
export const isArray = (arr) => Array.isArray(arr);
export const isObject = (obj) => obj !== null && typeof obj === 'object' && !Array.isArray(obj);
export const isString = (val) => typeof val === 'string';
export const isNumber = (val) => typeof val === 'number' && !isNaN(val);
export const isBoolean = (val) => typeof val === 'boolean';
export const isFunction = (val) => typeof val === 'function';
export const generateUUID = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2);
export const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
export const randomFloat = (min, max) => Math.random() * (max - min) + min;
export const clamp = (num, min, max) => Math.min(Math.max(num, min), max);
export const lerp = (start, end, amt) => (1 - amt) * start + amt * end;
export const degreesToRadians = (deg) => deg * (Math.PI / 180);
export const radiansToDegrees = (rad) => rad * (180 / Math.PI);
export const sumArray = (arr) => arr.reduce((a, b) => a + b, 0);
export const avgArray = (arr) => arr.length ? sumArray(arr) / arr.length : 0;
export const capitalize = (s) => s.charAt(0).toUpperCase() + s.slice(1);
export const lowercase = (s) => s.toLowerCase();
export const uppercase = (s) => s.toUpperCase();
export const trimSpaces = (s) => s.trim();
export const isNotEmpty = (val) => val !== null && val !== undefined && val !== '';
export const isEmpty = (val) => !isNotEmpty(val);
export const toFixed2 = (num) => Number(num).toFixed(2);
export const toFixed4 = (num) => Number(num).toFixed(4);
export const parseJSON = (str) => { try { return JSON.parse(str); } catch { return null; } };
export const stringifyJSON = (obj) => JSON.stringify(obj, null, 2);
export const getTimestamp = () => Date.now();
export const getISODate = () => new Date().toISOString();
export const getYear = () => new Date().getFullYear();
export const getMonth = () => new Date().getMonth() + 1;
export const getDay = () => new Date().getDate();
export const addDays = (d, days) => new Date(d.getTime() + days * 86400000);
export const subDays = (d, days) => new Date(d.getTime() - days * 86400000);
export const isArray = (arr) => Array.isArray(arr);
export const isObject = (obj) => obj !== null && typeof obj === 'object' && !Array.isArray(obj);
export const isString = (val) => typeof val === 'string';
export const isNumber = (val) => typeof val === 'number' && !isNaN(val);
export const isBoolean = (val) => typeof val === 'boolean';
export const isFunction = (val) => typeof val === 'function';
export const generateUUID = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2);
export const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
export const randomFloat = (min, max) => Math.random() * (max - min) + min;
export const clamp = (num, min, max) => Math.min(Math.max(num, min), max);
export const lerp = (start, end, amt) => (1 - amt) * start + amt * end;
export const degreesToRadians = (deg) => deg * (Math.PI / 180);
export const radiansToDegrees = (rad) => rad * (180 / Math.PI);
